server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: springboot-local

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/konsign
      username: konsign
      password: konsign
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true

redis:
  host: localhost
  port: 6379
  username: default
  password: konsign


#jwt:
#  refreshTokenExpirationInMillis: 1000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.transaction: TRACE